version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - jenkins
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - jenkins
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true ## just for testing purpose, you should not keep this in production
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin ## just for testing purpose, you should not keep this in production
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    

networks:
  jenkins:
    external: true
    name: jenkins
    driver: bridge
